var tooltips = {
    'prologue_steadfast': "Situated in Black Ridge, deep in the heart of the Canadian Rockies, this top-secret underground facility was established in 2028 in response to increased global instability.\n\nOperating under the guise of a Canadian Air Force base, the site is in fact headed up by North American Strategic Aerospace Command or NARCOM. A combined organization of the United States and Canada that provides aerospace warning, air sovereignty, and protection for Northern America.\n\n...",
  
    'prologue_exposure': "The Black Ridge military base was designed to appear like any other: organized, secure, and remote. Settled near the north bay of British Columbia, what appeared to be a standard Canadian installation hid a catastrophic mistake that tore the world asunder. Underneath Black Ridge’s surface was a conspiracy spearheaded by North American military researchers, who had spent years burying their mistake - triggering the Blackout.\n\nOperation: Steadfast Refuge sought to protect America from the worsening climate but resulted in tragedy after an untimely test went catastrophically wrong. Despite doing untold damage, research at Black Ridge resumed shortly after as various high-ranking military officers and government agencies sought to finish the work they had started, no matter the cost. Unfortunately, they never had the chance to fulfill their objective.\n\n...",
  
    'prologue_shearwater': "The jointly operated American-Canadian facility in Canada's Black Ridge mountains was part of a top-secret initiative designed to stabilize the weather in North America. Despite being in direct conflict with the ENMOD Convention, the facility came online in 2038 until structural damage, following an attack, prompted its closure in 2042.\n\nBy design, the science worked by first generating an energy field that stretched from the facility’s ringed structure into Earth’s lower ionosphere. An orbiting satellite – called Shearwater-1 – then deployed a package of particles that interacted with the field and became energized. Only once the particles traveled back into the troposphere could they tame weather patterns over a vast region.\n\n...",

    'prologue_voros': "Descended from three generations of dedicated Hungarian scientists, Dr. Gedeon Voros grew up believing humanity’s salvation lay in creating cutting-edge technology. His initial forays into climate change research were applauded by the community, but Voros struggled to find funding. It wasn’t until he published a quietly received paper about the theory of weather manipulation that Voros drew attention from a joint North American military project. They offered both significant funding and citizenship, which Voros accepted, becoming lead scientist at the Black Ridge facility in Canada.\n\n...",

    'prologue_blackout': "...\n\nSadly, the theory was never proven as the first full-scale test ended in catastrophic failure. On March 12, 2040 a deployment malfunction took Shearwater-1 off course where it collided with a U.S. Communications Satellite and subsequently crashed in Doha, Qatar. The resulting space debris tore through many other orbiting bodies and destroyed 50-70% of Earth’s satellite network, instantly doing cataclysmic damage.\n\n...",

    'prologue_kayvan': "“I thought I was an objective journalist, seeking to find out if No-Pats were the villains the world made them out to be. Little did I know that the answer would take me around the globe to places now engulfed by war. I set out to report their story, but it has become my own. This is our journey.”\n\n...",

    'prologue_hourglass': "Doha was a gem in the center of Qatar: a shining example of how far technology could reach in a hostile landscape, until finally exceeding its grasp. Once home to millions, the slow erosion of the desert began to ebb away at the luxury skyscrapers and tourist attractions, until daily sandstorms stole the life out of Doha’s isolated paradise. As local instability grew, the police cracked down on any sign of rebellion, fearing the city could become yet another Non-Patriated flashpoint.\n\n...",

    'prologue_journey': "SEPTEMBER 12TH, 2041\nDOHA, QATAR\n\nIt all began a year ago, surfing a darknet browser in my hometown of Doha - back when it was still inhabited by people. As a journalist I’d become keenly interested in the issue of armed No-Pats, trying to find a contact within the ranks of these stateless soldiers. Finally, at 3:28 AM, an anonymous source DM’d me, claiming to be the most wanted man alive - the commander of the largest contingent of No-Pat forces, known to the world simply as “Oz”.\n\nI’d gotten such messages before, but it was never the real Oz. Some came from government agents waging anti-No-Pat campaigns and one guy had even accused me of being Oz, hiding in plain sight. But this was different, if for no other reason than the chat ended with me needing to flee the country as the Qatari Police broke down my door for aiding a terrorist.\n\n...",

    'prologue_exodus': "The MFS-04 Exodus is a combat ship formerly of the Royal Navy. Taken by Oz following the first disbandment of the British Armed Forces, he handed command of the vessel to Irish in 2042 with orders to form a specialist unit that would undertake operations to further the No-Pat cause. In addition to its combat capabilities, the ship performed many humanitarian missions and provided safe passage for No-Pat refugees in need of aid.\n\n...",

    'prologue_irish': "As a child, Irish idolized his uncle. The pair formed a strong bond during the many camping trips in upstate New York where the boy learned important lessons about working hard and doing the right thing, but above all that life should be lived with “No fucking regrets!”\n\nIrish joined the Marine Corps and proved himself a highly capable soldier across a series of international deployments. He was earmarked for a specialist unit called Tombstone Squad and overcame his long standing alcohol addiction to earn his place. The squad was one of the fiercest units in the U.S. military and was called upon for only the toughest missions. One of their last ops involved a Chinese coup and a nearly averted world war that left Irish embittered by the loss of his compatriots.\n\n...",

    'prologue_rao': "As a boy, Rao was struck down by childhood leukemia. He spent many weeks and months in hospital undergoing treatment that often left him bedridden. Becoming increasingly isolated and lonely, he found an online community and learned how to code. It soon became clear that Rao was a prodigious talent, and in an effort to impress his friends, Rao hacked his school’s computer network to inflate his companions’ grades. When his efforts were traced back to his parents’ home in Mumbai, he was sent away to live with his aunt and uncle as punishment.\n\n...",

    'prologue_prelude': "OCTOBER 20TH, 2042\nMEDITERRANEAN SEA\n\nLondon is three feet under water – the failed capitol of a failed state. Why Oz rerouted the Exodus there was a mystery, one that only heightened when Captain Kimble “Irish” Graves went ashore alone and returned with a bleeding Marine, a briefcase, and instructions for an ocean rendezvous.\n\nIt should have been a simple hand off but something made Irish change his mind.\n\n...",

    'prologue_mithali': "Mithali was born in 2020 to working class parents in Alang, India. Her father worked at the ship-breaking yard where she ran among the rusted hulks, developing a talent for trading information instead of parts. Her extroverted nature and knack for local dialects eventually earned attention - just after turning eighteen, an anonymous benefactor paid for Mithali to attend the journalism program at the Indian Institute of Mass Communication.\n\n...",

    'prologue_lis': "As the daughter of wealthy parents, Lis experienced an upbringing more privileged than most of her peers. She attended the prestigious Nord Anglia boarding school and initially did well in her studies. However, her educational performance began to decline as world events worsened and her own country became embroiled in crisis. \n\nWith a growing desire to do something with her life that mattered, Lis defied her parent’s wishes and enlisted in the Polish military. Despite being cut off from her family, Lis forged ahead with her decision in the hope that one day her family could forgive her.\n\n...",
  }