var tooltips = {
    'prologue_baltic': "In 2028 an uncontrollable fire had begun to sweep most of Eastern Europe, slowly spreading and destroying farmland from Kyiv to Berlin. By 2030, with the “Breadbasket of Europe” decimated, the world suffered an extreme shortage of grain and an alarming drop in food production, ultimately entering the Second Great Depression.\n\n...",
  
    'prologue_steadfast': "Situated in Black Ridge, deep in the heart of the Canadian Rockies, this top-secret underground facility was established in 2028 in response to increased global instability.\n\nOperating under the guise of a Canadian Air Force base, the site is in fact headed up by North American Strategic Aerospace Command or NARCOM. A combined organization of the United States and Canada that provides aerospace warning, air sovereignty, and protection for Northern America.\n\n...",
  
    'prologue_exposure': "The Black Ridge military base was designed to appear like any other: organized, secure, and remote. Settled near the north bay of British Columbia, what appeared to be a standard Canadian installation hid a catastrophic mistake that tore the world asunder. Underneath Black Ridge’s surface was a conspiracy spearheaded by North American military researchers, who had spent years burying their mistake - triggering the Blackout.\n\nOperation: Steadfast Refuge sought to protect America from the worsening climate but resulted in tragedy after an untimely test went catastrophically wrong. Despite doing untold damage, research at Black Ridge resumed shortly after as various high-ranking military officers and government agencies sought to finish the work they had started, no matter the cost. Unfortunately, they never had the chance to fulfill their objective.\n\n...",
  
    'prologue_shearwater': "The jointly operated American-Canadian facility in Canada's Black Ridge mountains was part of a top-secret initiative designed to stabilize the weather in North America. Despite being in direct conflict with the ENMOD Convention, the facility came online in 2038 until structural damage, following an attack, prompted its closure in 2042.\n\nBy design, the science worked by first generating an energy field that stretched from the facility’s ringed structure into Earth’s lower ionosphere. An orbiting satellite – called Shearwater-1 – then deployed a package of particles that interacted with the field and became energized. Only once the particles traveled back into the troposphere could they tame weather patterns over a vast region.\n\n...",

    'prologue_voros': "Descended from three generations of dedicated Hungarian scientists, Dr. Gedeon Voros grew up believing humanity’s salvation lay in creating cutting-edge technology. His initial forays into climate change research were applauded by the community, but Voros struggled to find funding. It wasn’t until he published a quietly received paper about the theory of weather manipulation that Voros drew attention from a joint North American military project. They offered both significant funding and citizenship, which Voros accepted, becoming lead scientist at the Black Ridge facility in Canada.\n\n...",

    'prologue_blackout': "...\n\nSadly, the theory was never proven as the first full-scale test ended in catastrophic failure. On March 12, 2040 a deployment malfunction took Shearwater-1 off course where it collided with a U.S. Communications Satellite and subsequently crashed in Doha, Qatar. The resulting space debris tore through many other orbiting bodies and destroyed 50-70% of Earth’s satellite network, instantly doing cataclysmic damage.\n\n...",

    'prologue_kayvan': "“I thought I was an objective journalist, seeking to find out if No-Pats were the villains the world made them out to be. Little did I know that the answer would take me around the globe to places now engulfed by war. I set out to report their story, but it has become my own. This is our journey.”\n\n...",

    'prologue_hourglass': "Doha was a gem in the center of Qatar: a shining example of how far technology could reach in a hostile landscape, until finally exceeding its grasp. Once home to millions, the slow erosion of the desert began to ebb away at the luxury skyscrapers and tourist attractions, until daily sandstorms stole the life out of Doha’s isolated paradise. As local instability grew, the police cracked down on any sign of rebellion, fearing the city could become yet another Non-Patriated flashpoint.\n\n...",

    'prologue_journey': "SEPTEMBER 12TH, 2041\nDOHA, QATAR\n\nIt all began a year ago, surfing a darknet browser in my hometown of Doha - back when it was still inhabited by people. As a journalist I’d become keenly interested in the issue of armed No-Pats, trying to find a contact within the ranks of these stateless soldiers. Finally, at 3:28 AM, an anonymous source DM’d me, claiming to be the most wanted man alive - the commander of the largest contingent of No-Pat forces, known to the world simply as “Oz”.\n\nI’d gotten such messages before, but it was never the real Oz. Some came from government agents waging anti-No-Pat campaigns and one guy had even accused me of being Oz, hiding in plain sight. But this was different, if for no other reason than the chat ended with me needing to flee the country as the Qatari Police broke down my door for aiding a terrorist.\n\n...",

    'prologue_nopat': 'The official term Non-Patriated was coined in 2035 by a joint international council that sought to process and manage the refugees displaced by the European crisis.\n\nMultiple resettlement camps were established throughout the world, often in poorer countries that could be coerced with the promise of aid. Attempts were made over the years to relocate No-Pats to other countries, but nothing could be formulated, leaving many languishing in camps that were often beset by unsanitary conditions and food shortages.\n\n...',

    'prologue_exodus': "The MFS-04 Exodus is a combat ship formerly of the Royal Navy. Taken by Oz following the first disbandment of the British Armed Forces, he handed command of the vessel to Irish in 2042 with orders to form a specialist unit that would undertake operations to further the No-Pat cause. In addition to its combat capabilities, the ship performed many humanitarian missions and provided safe passage for No-Pat refugees in need of aid.\n\n...",

    'prologue_oz': "Loyiso was born in 2003 in a small town situated in South Africa’s Richtersveld. His father, Themba, a local government officer, was a prominent and well-respected figure in the community. As far as Loyiso was concerned, Themba could do no wrong. That was until Wellspring arrived. \n\nThe U.S. company secured mining rights for the whole of South Africa and built a series of processing facilities across the Richtersveld, one of which overlooked Loyiso’s village. While jobs and investment were welcome benefits, hidden dangers loomed.\n\n...",

    'prologue_irish': "As a child, Irish idolized his uncle. The pair formed a strong bond during the many camping trips in upstate New York where the boy learned important lessons about working hard and doing the right thing, but above all that life should be lived with “No fucking regrets!”\n\nIrish joined the Marine Corps and proved himself a highly capable soldier across a series of international deployments. He was earmarked for a specialist unit called Tombstone Squad and overcame his long standing alcohol addiction to earn his place. The squad was one of the fiercest units in the U.S. military and was called upon for only the toughest missions. One of their last ops involved a Chinese coup and a nearly averted world war that left Irish embittered by the loss of his compatriots.\n\n...",

    'prologue_rao': "As a boy, Rao was struck down by childhood leukemia. He spent many weeks and months in hospital undergoing treatment that often left him bedridden. Becoming increasingly isolated and lonely, he found an online community and learned how to code. It soon became clear that Rao was a prodigious talent, and in an effort to impress his friends, Rao hacked his school’s computer network to inflate his companions’ grades. When his efforts were traced back to his parents’ home in Mumbai, he was sent away to live with his aunt and uncle as punishment.\n\n...",

    'prologue_mithali': "Mithali was born in 2020 to working class parents in Alang, India. Her father worked at the ship-breaking yard where she ran among the rusted hulks, developing a talent for trading information instead of parts. Her extroverted nature and knack for local dialects eventually earned attention - just after turning eighteen, an anonymous benefactor paid for Mithali to attend the journalism program at the Indian Institute of Mass Communication.\n\n...",

    'prologue_lis': "As the daughter of wealthy parents, Lis experienced an upbringing more privileged than most of her peers. She attended the prestigious Nord Anglia boarding school and initially did well in her studies. However, her educational performance began to decline as world events worsened and her own country became embroiled in crisis. \n\nWith a growing desire to do something with her life that mattered, Lis defied her parent’s wishes and enlisted in the Polish military. Despite being cut off from her family, Lis forged ahead with her decision in the hope that one day her family could forgive her.\n\n...",

    
    'zero_darkmarket': "The Dark Market is a coalition of intelligence operatives, arms dealers, crime lords, military contractors, and data brokers from the various countries that collapsed in the late 2030s. While they slowly rose to prominence during this period, their ascension into an omnipotent enterprise occurred during the fallout from the Blackout.\n\nUsing a non-satellite reliant communication network, the Dark Market became the de facto organization for the trade and purchase of all illicit materials, goods, and services, including weapons, military supplies, intelligence, mercenaries, and armies.\n\n...",

    'zero_crawford': "Born in London, Crawford was the youngest of three siblings. His parents were both civil servants, with his father a rising star as General Secretary within the UK’s largest trade union.\n\nCrawford was only 10 when his father died of a heart attack. The family were forced to move in with the father’s estranged uncle, Martin Crawford, a business mogul in the North East of England – and known figurehead in the local criminal underworld. Crawford was enthralled by the man – especially his gun collection – and he soon filled the paternal void the boy craved.\n\n...",

    'zero_liquidators': "A ruthless mercenary squad under the purview of the Dark Market, the Liquidators are highly trained operators who specialize in “involuntary asset liquidation.” They execute competitors, capture areas and technology critical to the Dark Market’s business plans, and assist allied companies.\n\n...",

    'zero_stranded': "At the time of its creation in 1913, Gatun Lake was the largest manmade lake in the world. Designed to aid in the formation of the Panama Canal, it helped shepherd ships and trade for decades. Then the tides began to turn.\n\nClimate change brought a mix of devastating storms and long dry periods, stranding ships in the lake as their crews were forced to evacuate. Out of desperate need to keep the rest of the Canal alive, Gatun Lake was cut off and left to wither. By 2037 the water finally drained away, leaving moored ships in the sand to become rusting monuments of what once was. Yet their value as vehicles of trade was ready to be swept up by the highest bidder.\n\n...",

    'zero_wolff': "Wolff was born in 1995 in Palo Alto, California. He showed an early aptitude for his studies and graduated high school at fifteen. An athletics scholarship earned him enrollment at Indiana University a year later, where he excelled on the wrestling team. Shortly after, Wolff was approached by the university’s ROTC program and signed up to be a cadet.\n\nAt twenty, Wolff graduated with a political science degree and entered the Army proper. He was cherry-picked to apply for the 75th Ranger Regiment, and passed his assessment with flying colors before being deployed to Afghanistan. Known for both his ardent patriotism and stoic presence under fire, Wolff entered Delta Force selection after signing up for his second tour and became an operator.\n\n...",

    'zero_falck': "Growing up, Falck was driven to study medicine after watching her father lose his battle with cancer. The early 2000’s conflicts in the Middle East curtailed her education, causing her to enlist in the German Army where she trained as a combat medic. After tours in both Iraq and Afghanistan, she returned home and was assigned to the Rapid Forces Division where she took part in many joint missions with European allies.\n\nDespite a highly decorated career, Falck decided to retire from the army and finish her studies. She eventually graduated to become a respected trauma surgeon in one of Cologne’s most prestigious hospitals.\n\n...",

    'zero_angel': "Born the son of an auto mechanic, Angel tinkered with cars from an early age, usually in an effort to increase their speed. Recognizing his son’s prowess and determined to keep him safe, his father allowed him to work on an old WWII fighter engine he had long neglected.\n\nAfter several years Constantin had fully restored the engine, as well as adding a few of his own personal modifications. But unknown to his father he’d attached it to an old plane chassis. It was a short test flight that ended with the teenager barely escaping with his life. An incident that earned him the nickname, “Angel.”\n\n...",

    'zero_paik': "Born in Gwangju, South Korea, Paik was an only child and an introvert by nature. Both her parents had demanding jobs and would often place Paik in the care of her great grandfather, Sang-chul. The quiet old man wanted nothing more than to spend his days playing the strategy game, Baduk. In Paik he found the perfect companion. As soon as he introduced her to the 19x19 wooden grid and its black and white stones, she was transfixed.\n\nWhat on the surface seemed simple was far more complex than Paik had ever imagined. More combinations could be reached on this small board than there were atoms in the universe. After a couple of years under Sang-chul’s tutelage, Paik became an excellent practitioner. On special occasions they would venture to the city parks in Seoul where Sang-chul pitted the young girl against much older players; he never tired of seeing that look of utter confusion as it dawned on them they were going to lose.\n\n...",

    'zero_boris': "Born in Omsk, Siberia, Boris’ upbringing was marred by struggle as his family fought to keep their farm alive after the collapse of the Soviet Union and the agricultural transformation that followed.\n\nDesperate to escape the back-breaking life laid out before him, Boris took inspiration from the local legend that a distant relative was one of the infamous WW2 Night Witches - the all-female Bomber Regiment - and left home at 18 with the hope of joining the Russian Air Force.\n\n...",

    'zero_dozer': "Dozer grew up in Mexico to a family of migrant workers. At the age of 10, he and his family undertook the dangerous journey into Texas and settled in El Paso to make a life for themselves.\n\nThroughout his adolescence, Dozer struggled with his identity, not knowing where he truly belonged. When he discovered the U.S. Army offering the chance for citizenship he joined up and completed his first tour of duty with the 20th Special Forces Group deployed in Latin America.\n\n...",

    'zero_mackay': "Mackay was born on a Canadian army base where his father served as an officer. His mother was an absent figure through most of his childhood and spent long stretches in hospital to treat severe depression. Military life meant the family never stayed in on location for more than a couple years. As such, Mackay came to rely heavily on the one constant in his life: his father. Together, they formed an unbreakable unit.\n\nAt 18, Mackay followed his father’s wishes and joined the military where he excelled in survival and marksmanship training. He rose through the ranks and joined Joint Task Force 2. Deployed in multiple NATO-led missions in Eastern Europe, their primary task was the elimination of terrorist cells that were exploiting the region’s worsening crisis.\n\n...",

    'zero_casper': "Despite growing up in a stable family, Wikus battled with anxiety during his teenage years. His father introduced him to running as a way to cope. Every morning the pair would hit the Sea Point Promenade and for that 11km, Wikus started to find peace. Over the years the boy strengthened his mind and body into an impenetrable fortress. The runs became longer and harder to the point his father wasn’t able to keep up. So focused was Wikus by then, it was like he was running alone anyway.\n\nEager to test himself physically and mentally, Wikus joined the military and one of his first tours was to assist a peacekeeping force stationed in the Democratic Republic of the Congo. His budding marksmanship skills and mental fortitude made him an ideal candidate to keep watch alone from long distances.\n\n...",

    'zero_sundance': "Sundance was orphaned while still a toddler when Paris was devastated by a nuclear attack. As the city underwent mass evacuation, Sundance was moved to a large children’s home in Lyon. Growing up was a traumatic period for them, not only dealing with issues of identity but also navigating the shifting power struggles between the other children.\n\nAs they reached their late teens, Sundance fell in with the local Le Milieu after a confrontation with a nightclub bouncer showcased their abilities as a fighter. The criminal family took Sundance into their care, teaching them to provide security for the organization’s smuggling ops. For the first time in their life, Sundance found something they were good at and they excelled at their job.\n\n...",


    'master_wildcard': "SUMMARY\n\nThe purpose of CIA Operation: WILDCARD was to secure HVT Charlie Crawford. It was to be executed in tandem with U.S. Forces’ Operation: DRYDOCK, the proportionate response to the Dark Market’s assault on the Black Ridge Facility.\n\nOn January 25 at 1400, Fireteam Exodus infiltrated the STG Ceres posing as plainclothes weapons buyers. For this mission, Fireteam Exodus included NP Specialists Angel, Falck, Mackay, Boris, Paik, and Dozer acting under the command of Special Operations Officer Noah Wolff.\n\n...",

    'master_blasco': "Born in Colón, Panama to middle-class Spanish parents, Camila’s childhood by the coast instilled a lifelong love of the ocean. This idyllic upbringing was shattered by a freshwater supply crisis that devastated the country. Desperate to stabilize her life, Camila’s mother and father sent their daughter to live with her grandfather in Vigo, Spain.\n\nA retired commercial fisherman, Antonio would often take Camila out on his boat with a pair of rods and enough bait to last the day. The proud Spaniard taught her to survive off the sea and often regaled Camila about their family history fighting Franco’s army in the bloody Spanish civil war. Inspired by their sacrifice, Camila enrolled at the prestigious Naval Academy in nearby Marin, meeting qualifications to join the Fuerza de Guerra Naval Especial (FGNE) as a special forces officer.\n\n...",

    'master_broker': "As maintaining secrecy is of paramount importance, the Dark Market Council uses The Broker to provide contract work to No-Pats around the world.\n\nThe Broker is the advocate who speaks on behalf of the Dark Market Council. Their role is simple – succinctly deliver contracts to No-Pats at the Council’s request.\n\n...",

    'master_council': "The Dark Market is led by The Council, three individuals who each lead one of the organization's three primary ventures – arms, militias, and intelligence.\n\nThe Arms venture is led by The Jaguar. Originally from Argentina, he led a criminal empire supplying weapons and military supplies to clients all over the world. Sourcing most of his supplies from No-Pat countries, when their governments fell his supply chains dried up. He could only watch in anger as former allies swooped in and stole his customers.\n\n...",

    'master_batista': "Formerly a Lieutenant Colonel of the Brazilian Armed Forces, Batista has led the Skullcaps for several years, though that wasn’t always the plan. After parting ways with the army, Batista joined the Dark Market and worked under the Jaguar, where he founded The Liquidators.\n\nHe oversaw their operations for several years. Though he found himself missing field work, Faren was thankful. His partner reminded him the desk job kept him coming home every night, not to mention the compensation meant their four children were set for life.\n\n...",


    'escalation_nordvik': 'Nordvik was formed in Gothenburg, Sweden in 2028 by Måns Nordqvist, Erik Nilsson, and Oscar Bergman. Initially an agricultural equipment manufacturer focused on heavy-duty machinery for corporate farming, Nordvik’s ambitions far exceeded the agroindustry.\n\nFor their founders, their company represented the litmus test for the future of automation. Nordqvist, Nilson and Bergman were from the technology sector, where each pioneered automation, robotics, and large-scale 3D printing. Every one of their factories is fully automated without any permanent personnel. As such, most of their factories were constructed in remote, isolated locations.\n\n...',

    'escalation_zain': 'Zain was born in Egypt at a time of great economic instability. As the infrastructure of the Cairo Governorate continued to disintegrate, Zain’s parents lost their jobs and eventually their home. During this period Zain’s mother became a full-time activist, fighting for the rights of everyday people struggling to survive. Zain would often help his mother paint placards and join her on marches. The experience deepened their bond and inspired one another’s commitment to the cause.\n\nWhen Zain’s mother was suddenly diagnosed with Parkinsons, his father made the difficult decision to leave New Cairo City for the country so he could better care for his wife – it was time for others to take up the fight. Zain felt lost and his disillusionment grew.\n\n...',

    'escalation_spearhead': 'War is an opportunity. For multinational behemoth Nordvik, it was an opportunity to make more money. That meant adapting their cutting-edge industrial resources into a commodity everyone wanted: weapons.\n\nProduction began in a climate stable, remote mountain plateau in Northern Scandinavia. The factory – formerly in the business of manufacturing heavy-duty farming machinery – was one of many fully autonomous, self-sufficient sites that eliminated the need for any human presence. Land vehicles, tanks and drones now graced the assembly lines in staggering numbers, and secured Nordvik as a global leader in weapons manufacturing, as they advertised pure neutrality when it came to selling their products.\n\n...',

    'escalation_bergman': 'One of the founders of Nordvik, Oscar Bergman, was born in Gothenburg, Sweden in 1980. He adapted many designs and learnings from his grandfather Fredrik, who had survived a long career as an oil plant farmer in the central Swedish lowlands, and eventually patented several inventions in the field. These would serve as Nordvik’s foundation as they invested in corporate farming machinery and began to expand outward through the agroindustry.\n\nBergman’s 3D printers in particular were a vital feature, and he backed his partners Nilsson and Nordqvist as they designed Nordvik’s first “Lights Out” factory, which set the standard for the future of automation. Their ambitions soon surpassed simple equipment as the company began taking contracts from the military industrial sector, and producing materiel en masse.\n\n...',

    'escalation_collapse': 'Worsening climate and economic security exacerbated the divisions that lay at the heart of the EU’s complex network of treaties and internal power structures. As the Union’s poorest members bore the brunt of this deepening crisis, they were the first to fall, sparking a refugee crisis along numerous borders.\n\nFollowing the damage wrought by the Baltic firestorm and the collapse of the Euro, Germany’s government dissolved on August 8, 2035. As Europe’s most powerful state, it was impossible to stop the deepening fault lines of instability — a month later the European Union officially disbanded.\n\n...',

    'escalation_warmachine': 'SUMMARY\n\nThe purpose of CIA Operation: WAR MACHINE was twofold – secure the HVTs Rasheed Zain and Gedeon Voros, and terminate Project: SILVER SPEAR.\n\nOn March 14 at 1300, Fireteam Exodus infiltrated the Nordvik Facility. For this mission, Fireteam Exodus included NP Specialists Crawford, Lis, Casper, Dozer, Rao and Mackay acting under the command of Special Operations Officer Noah Wolff.\n\n...',

    'escalation_manifest': 'From the outside, it appeared Brani Island had simply missed the climate apocalypse. The city and trade ports thrived, using automated labor to control everything from tide tracking to gate controls. In 2030, Singapore and America entered partnership to create a massive sea wall. Completed in 2036, this protective wall held rising waters at bay and allowed Singaporean citizens to keep an oncoming crisis out of sight and out of mind. The astronomical wealth acquired from keeping a vital international port running was constantly reinvested into the island, and projected a clean and untouchable image to the rest of the world.\n\n...',

    'escalation_orbital': 'For years, Kourou was a highlight of European unification and success. The European Space Agency maintained the cutting-edge Guiana Space Center with launches live-streamed to the public all over the world, hoping to make old-fashioned “international space race” conflicts a thing of the past.\n\nThey succeeded until the Collapse of the EU. By 2036, the EUSA ceased operations, leaving the French Guiana launch site largely abandoned, safe for a small group of personnel and soldiers who remained, determined to protect the symbolic peacekeeper site.\n\n...',

    'escalation_breakaway': 'Even in a world constantly afflicted by environmental collapse, the hunger for fossil fuels has never ceased. First claimed by Norway and usurped by Russia in 2038, Queen Maud land and the Riiser-Larsen sea have been choked by oil drilling equipment ever since as platforms operated twenty-four seven to feed military interests across the globe. Changes in local temperature wreaked havoc on vital snow packs and glaciers, causing a ripple effect on the surrounding region as melted runoff poured into the ocean.\n\nIts remote location and perpetual violation of international law meant that much of the technology ran on fumes, often hastily repaired from a dwindling supply of scrap and backup parts. Being assigned to the Queen Maud defensive force was seen as a tacit punishment, and the company responsible for processing oil - Chistaya Neft - kept the entire operation on a skeleton crew.\n\n...',


    'eleven_flashpoint': 'The Richtersveld was once the only arid biodiversity hotspot on Earth, containing a wealth of unique flora and fauna that bloomed under the African sun. Yet when global instability drove tourists and rangers out of the region, an American-backed corporation took the opportunity to set up illegal resource extraction along the Namibian border.\n\nReckless use of equipment slowly stripped the surrounding desert of life as already high temperatures turned lethal, and chemical runoff contaminated groundwater in nearby villages – one of which was home to Loyiso Okusanya, the man who would one day come to be known as Oz. When the discovery of a rare fuel component was discovered, a massive investment from several American funds was delivered with the intention of creating rocket fuel on the cheap. But the same heat created by the development complex doomed the project to failure.\n\n...',

    'eleven_wellspring': 'In 2037, a fire of unknown origin erupted inside of one of Wellspring’s processing stations inside the Richtersveld. Reports are mixed as to whether the ignition occurred due to windstorms damaging valuable fiberglass components, a flaw in the fuel formula, or a lack of safety protocols regarding their industrial waste barrels. One barrel exploded upon contact with the fire, causing a cascade of damage throughout the entire facility and forcing all Wellspring personnel to evacuate.\n\n...',

    'eleven_namaqualand': 'Twenty years ago, the Richtersveld was one of the natural wonders of the world. After the catastrophic incident at the Wellspring factory poured toxins into the air, ground, and nearby river, it was abandoned.\n\nIn 2043, it became the cradle of the No-Pat independence movement led by Oz, who was born and raised in one of the Nama villages. His ideal “borderless nation” welcomes all No-Pats regardless of past allegiances, and seeks to unify those who have been harmed by the ongoing war between U.S. and Eastern Forces.\n\n...',

    'eleven_curtain': 'The purpose of CIA Operation: Curtain Call was to find and eliminate the No-Pat terrorist known as “Oz.”\n\nWhat follows is a transcription excerpt from Operation: Curtain Call briefing between SOO Wollff and SC Atticus.\n\n...',

    'eleven_capetown': 'DATE: NOVEMBER 5TH, 2043\nTO: CIA DIR. M. RENOIT\nFROM: N. WOLFF\n\nRE: EMBEDDED ASSETS DEBRIEF - CAPE TOWN\n\nOn October 30, 2043 at 0300, my strike team embedded in Cape Town, South Africa failed to check in, and stopped responding to all communications. After seventy-two hours of no contact, a drone was sent into the bunker, and it was discovered that every agent present was dead.\n\n...',

    'eleven_discarded': 'In many ways, the ship-breaking yard in Alang, India was the biggest graveyard in the world. Massive skeletons of the largest vessels in the world were brought to its shores to be stripped down for parts, giving everything from old steel to the captain’s chair a new purpose. It was dangerous, often destructive work, as years of deterioration exposed the many scrapper crews to lead, obscene heat, and sometimes even nuclear material.\n\n...',

    'eleven_ozspeech': '[Transcript of Oz’s speech at the Battle of Richtersveld. With Wolff’s FALT forces closing in on their No-Pat sanctuary, Oz broadcast a speech across all No-Pat frequencies – an eleventh hour plea to join their cause and fight for their future.]\n\nOZ: To every No-Pat deployed here today, whether you take up arms to further our cause, or to crush it – I ask you to hear me.\n\nThis battle is a defining moment in our history. It is a date that future generations will have engraved on their hearts – for it is the day No-Pats fought back against the world’s imperialist aggressors.\n\n...',

    'eleven_falt': 'Originally an elite strike team operating within the Non-Patriated Counter Terrorism Unit, the Foreign Activities Liaison Team was a crown jewel of the CIA led by Officer Noah Wolff. Trained to drop into any locale at a moment’s notice, FALT infiltrates target locations as locals or allies by day, and transforms into a militarized threat by night, executing objectives before removing all trace of their presence.\n\n...',

    'eleven_silvermilitia': 'The operation was ultimately a failure. While they succeeded in wounding Oz, all members of Chaser-1 were declared KIA after a clash with Oz’s Silver Spear militia.\n\n...',

    'eleven_shearwater2': 'On Nov. 15, 2043, the Exodus specialists conducted a test of Project: Silver Spear. Activating the Shearwater-2 satellite, they triggered the formation of a superstorm near a Synseco facility in Egypt.This first test demonstrated the technology worked – and that land rehabilitation could begin.\n\nAfter its success, the satellite was again deployed in the Richtersveld, to transform the harsh landscape into a replenished ecosystem where life could flourish. Oz christened this land as a new home for No-Pats: Namaqualand.\n\n...',

    'eleven_renewal': 'From inside, the Wall looked like a miracle. Lush green crops flourished in the middle of the blazing, nigh-lethal desert, with spotless glass and top-tier technology highlighting a generosity and transparency that only a megacorp like Synseco Agritech could provide. Paradise was promised to Egyptians - and the Non-Patriated - who braved the heat and took a so-called “growth” employment contract, swearing to provide as much for Synseco and Synseco provided for them.\n\nOutside the Wall was a different story. Chains of massive concrete blocks and security fencing prevented everyone else living in the Eastern Desert from accessing Synseco’s massive reservoirs of water, despite a constant onslaught of deaths from drought and dehydration. Synseco’s aggressive protection of their modified crops led to entire villages being confronted by corporate security on the mere suspicion that local farmers were using stolen seeds.\n\n...',

    'eleven_leviathan': 'While the SPS Impávido is home to the most fearless No-Pats, Leviathan Division contains its most feared. Personally trained and led by Camila Blasco, Leviathans are soldiers who specialize in infiltration, sabotage, and shock-and-awe tactics designed to devastate much larger forces and take entire bases offline.\n\n...',


    'epilogue_renewalday': 'The 15th of November 2043. A powerful storm descended upon the desert near the Synseco facility in Egypt: Shearwater-2 had worked. Millions of No-Pats commemorate this event every year. They call it Renewal Day. A celebration of the moment Oz and his movement finally held the power to shape their own future.\n\nIn response, Western and Eastern forces launched an all-out assault on multiple No-Pat strongholds around the globe. The No-Pats fought back and dealt the superpowers a stunning defeat. Compounding America’s humiliation, Oz released evidence implicating the CIA–specifically one senior operative Noah Wolff–in a cover-up of their involvement in the 2040 Blackout. This revelation all but rendered the United States a global pariah and sent Wolff into hiding. His whereabouts are still unknown.\n\n...',

    'epilogue_erf': 'The European Recovery Foundation is a humanitarian organization dedicated to the restoration of the European Union and its member states. With headquarters in South Korea, the ERF primarily serves as a large aid foundation, while also maintaining its own peacemaker forces in order to stabilize various borders and supply chains across the world. They have endured criticism about their recruitment of No-Pat squads to serve as third parties in various tense conflicts, but so far, the ERF’s gambles have paid off.\n\n...',

    'epilogue_arkangel': 'Arkangel Corporation rose to prominence in the aftermath of Renewal Day 2043. Taking over the delivery of Shearwater weather technology from the Dark Market, the company worked with the faltering countries who called for aid, reinvigorating third world nations and fallen EU states with new life.\n\nArkangel positioned themselves as a neutral entity in the service of all nations - an enterprise invested in the betterment of humanity through the application of robotics and AI technologies, dedicated to improving a number of global industries including healthcare, manufacturing, business and transportation.\n\n...',

    'epilogue_blackburn': 'Henry was born in Buffalo, New York. He came from a long line of serving military personnel who’d fought in multiple wars. It only seemed right that Henry continued the Blackburn legacy.\n\nStaff Sergeant in the U.S. Marines, Henry fought in the war effort against the PLR in 2014 and went on to foil the plot to detonate a nuclear device on American soil. Despite his heroic actions, Blackburn was court-martialed for the killing of a superior officer and dishonorably discharged from the army. The disgraced soldier responded the only way his training would allow: he adapted.\n\n...',

    'epilogue_sli': 'As the demand for Shearwater satellites surged in the mid-2040s, so too did the demand for lithium ore. Arkangel established Shearwater Lithium Industries (SLI) in 2044 and expanded operations dramatically over the following year, building stations in Australia, Argentina, Canada and Chile. As compensation for the right to mine lithium, each country was given access to Shearwater weather satellites and financial incentives for the affected communities.\n\nWith its highly invasive and environmentally disruptive operations, SLI quickly found themselves ensnared in controversy. Reports highlighted that certain shortcuts to increase expediency had also triggered negative ecological effects in the regions. While SLI claimed confidently any damage inflicted on the environment would be fixed utilizing the very satellites the lithium was being mined for, this did little to dissuade angered communities.\n\n...',

    'epilogue_boreas': 'Boreas Research & Development was born out of an investment by one of Nordvik’s founders, Erik Nilsson. After he purchased rights to an abandoned bunker in the Scottish Hebrides, the newly created Boreas was put to work as a secret splinter cell investing in synthetic combat enhancements and AI-enhanced assistants. Eventually, the bunker was fully repurposed to develop a training ground for augmented soldiers and first-in-class laboratories.\n\n...',

    'epilogue_redacted': 'As part of their Cold War defense, Scotland developed strategic underground bunkers throughout the country, which remained manned but classified for decades before being shut down. One of these bunkers was in the Hebrides, with top scientists focused on biological containment and environmental sealing in case of nuclear destruction. The project was all but abandoned in the late 1990s.\n\nIn 2038, one of Nordvik’s founders purchased the rights to the bunker from the Royal government, intending to use the location for a secret splinter cell called Boreas Research & Development. This cell was directed to research synthetic enhancement and AI-enhanced assistants, and began stripping down the bunker to develop a training ground and leading-edge laboratories.\n\n...',

    'epilogue_bcs': 'On their face, Boreas Containment Services appear to be standard corporate guards. But under their bright clean uniforms are operatives recruited from spec op forces and PMCs, each one sworn to absolute secrecy when it comes to Boreas’ most extreme projects. Rather than answering to local staff, security breaches in the Scottish Hebrides labs are reported directly to Henry Blackburn, who controls the experiments on site as part of a classified wing of Arkangel.\n\n...',

    'epilogue_campbell': 'Former member of the SAS, Duncan Campbell became a trusted leader within Henry Blackburn’s inner circle and played a key role in Blackburn’s private military ventures throughout the 2020s.\n\nWhen the time came to form a security team to run the Boreas Hebrides laboratory, Blackburn brought in his long-time colleague to assist. As leader of Boreas Containment Services, Campbell was given full clearance and briefed on every aspect of the project. He was used to dealing with people, he knew how they operated. But synthetics - they were a mystery. And so was the AI powering them.\n\n...',

    'epilogue_aos': 'The Aurora Operating System (A.O.S.) is the reactive, intelligent core AI empowering the synthetic soldiers inside the Boreas bunker. Named for Aôs/Aurora, Boreas’ mother and the goddess of the dawn/ascendant sun, this AI controls the testing environments, locks, and other automated security measures throughout the facility. Its most important feature is devouring combat data and fusing it back into Project: Pallas, the program dedicated to developing tactics for a synthetic army.\n\nThe latter was considered deeply risky by Boreas’ Nordvik founder, but when control of the company was transferred to Henry Blackburn, he allowed A.O.S. more freedom, hoping to accelerate the project to a new level.\n\n...',

    'epilogue_reborn': '...\n\nNeural link technologies and prosthetics division: The team has done phenomenal work on the rollout of our “Warriors Reborn” initiative. We have restored more than 20,000 soldiers to full operational capacity through the application of our enhanced prosthetics. It is worth highlighting Boreas’ research in this field promises revolutionary developments and heralds a paradigm shift in infantry warfare.\n\n...',
  }